# Build Options
#   change to "no" to disable the options, or define them in the Makefile in 
#   the appropriate keymap folder that will get included automatically
#

# may want this later
TAP_DANCE_ENABLE = no

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif